"""Altered Building field in Apps table. Added unique constraint.

Revision ID: 1c3f1b8e9373
Revises: 12ee2543a4b9
Create Date: 2023-05-23 20:47:19.951497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3f1b8e9373'
down_revision = '12ee2543a4b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'apps', ['building'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apps', type_='unique')
    # ### end Alembic commands ###
