"""Added used field to app.

Revision ID: 2e31f88445d2
Revises: 88cbecd4f7c5
Create Date: 2023-06-03 00:15:15.208377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e31f88445d2'
down_revision = '88cbecd4f7c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'used')
    # ### end Alembic commands ###
