"""Buildings used field.

Revision ID: 528df9ff96d0
Revises: c0bed8dd9807
Create Date: 2023-06-03 14:05:40.733406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528df9ff96d0'
down_revision = 'c0bed8dd9807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('buildings_used', sa.ARRAY(sa.Integer()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'buildings_used')
    # ### end Alembic commands ###
