"""Delete image.

Revision ID: 88cbecd4f7c5
Revises: a6bdf4127d3e
Create Date: 2023-06-02 23:37:26.722583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cbecd4f7c5'
down_revision = 'a6bdf4127d3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
