"""Added new relations.

Revision ID: a6bdf4127d3e
Revises: c30cd032e39c
Create Date: 2023-05-30 11:25:39.499197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6bdf4127d3e'
down_revision = 'c30cd032e39c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'image')
    # ### end Alembic commands ###
