"""Drop unique constraint from building field in app.

Revision ID: c0bed8dd9807
Revises: 2e31f88445d2
Create Date: 2023-06-03 11:51:01.776789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bed8dd9807'
down_revision = '2e31f88445d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('apps_building_key', 'apps', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('apps_building_key', 'apps', ['building'])
    # ### end Alembic commands ###
