"""Altered price field to double.

Revision ID: c657589b8c56
Revises: 1c3f1b8e9373
Create Date: 2023-05-27 13:47:21.576898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c657589b8c56'
down_revision = '1c3f1b8e9373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'price',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using="price::double precision")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
