version: '3.8'

volumes:
  pg_12_data:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12.0-alpine
    volumes:
      - pg_12_data:/var/lib/postfresql@12/data/
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    env_file:
      - ./.env
    restart: always
